"""Q1/Q3/Q4/Q5 from the text outputs: dt, floors, energetics, cost. Read-only."""
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt          # noqa: E402
import common as C                        # noqa: E402

T0 = 8.64e7                               # restart time (rot 283)


def cost(d):
    a, fn = C.cyclelines(d)
    # per-100-cycle rate from the elapsed lines, excluding the first (startup) interval
    de = np.diff(a[:, 0])
    dc = np.diff(a[:, 1])
    dt = np.diff(a[:, 2])
    ok = de > 0
    return dict(cyc_per_s=float(np.median(dc[ok] / de[ok])),
                simsec_per_s=float(np.median(dt[ok] / de[ok])),
                cycles=int(a[-1, 1] - a[0, 1]),
                wall=float(a[-1, 0] - a[0, 0]),
                t0=a[0, 2], t1=a[-1, 2], dt0=a[0, 3], dt1=a[-1, 3])


def table(arms, rel_t0, title, fh):
    fh.write('\n### %s\n\n' % title)
    fh.write('| arm | cycles | wall s | cycles/s | sim s per wall s | dt first | dt last '
             '| median dt | sim time covered |\n|---|---|---|---|---|---|---|---|---|\n')
    for name, d in arms:
        c = cost(d)
        h = C.hst(d)
        fh.write('| %s | %d | %.0f | %.2f | %.1f | %.2f | %.2f | %.2f | %.3e |\n'
                 % (name, c['cycles'], c['wall'], c['cyc_per_s'], c['simsec_per_s'],
                    c['dt0'], c['dt1'], np.median(h[:, C.COL['dt']]),
                    h[-1, 0] - h[0, 0]))


def floors(arms, fh, title):
    fh.write('\n### %s\n\n' % title)
    fh.write('| arm | intervals | cycles | eos_dfloor total | per cycle | eos_efloor '
             'total | per cycle | eos_tfloor total | per cycle | eos_fail |\n')
    fh.write('|---|---|---|---|---|---|---|---|---|---|\n')
    for name, d in arms:
        names, cyc, a = C.evlog(d)
        idx = {n: i for i, n in enumerate(names)}
        ncyc = cyc[-1] - cyc[0]
        tot = a.sum(axis=0)
        fh.write('| %s | %d | %d | %.3e | %.2e | %.3e | %.2e | %.3e | %.2e | %d |\n'
                 % (name, a.shape[0], ncyc,
                    tot[idx['eos_dfloor']], tot[idx['eos_dfloor']] / max(ncyc, 1),
                    tot[idx['eos_efloor']], tot[idx['eos_efloor']] / max(ncyc, 1),
                    tot[idx['eos_tfloor']], tot[idx['eos_tfloor']] / max(ncyc, 1),
                    tot[idx['eos_fail']]))


def main():
    fh = open(C.OUT + 'logs_tables.md', 'w')

    fh.write('# Text-output tables (auto-generated by logs.py)\n')
    table(C.ARMS1, True, 'Comparison 1 (restart, rot 283): cost and dt', fh)
    table(C.ARMS2, False, 'Comparison 2 (cold start, nghost=3): cost and dt', fh)
    floors(C.ARMS1, fh, 'Comparison 1: floor counters (totals over the run)')
    floors(C.ARMS2, fh, 'Comparison 2: floor counters (totals over the run)')

    # rt_desum
    fh.write('\n### rt_desum (sweep-to-gas gap), comparison 1\n\n')
    fh.write('| arm | lines | mean rel | min | max |\n|---|---|---|---|---|\n')
    for name, d in C.ARMS1:
        a = C.desum(d)
        if a.shape[0] == 0:
            fh.write('| %s | 0 | - | - | - |\n' % name)
        else:
            fh.write('| %s | %d | %.4f | %.4f | %.4f |\n'
                     % (name, a.shape[0], a[:, 3].mean(), a[:, 3].min(), a[:, 3].max()))

    # energetics
    fh.write('\n### Energetics (hst), comparison 1: change over the run\n\n')
    fh.write('| arm | t span | dM/M | dE/E | KE first | KE last | ME first | ME last |\n')
    fh.write('|---|---|---|---|---|---|---|---|\n')
    for name, d in C.ARMS1 + C.ARMS2:
        h = C.hst(d)
        ke = h[:, 7:10].sum(axis=1)
        me = h[:, 10:13].sum(axis=1)
        fh.write('| %s | %.4e | %+.3e | %+.3e | %.4e | %.4e | %.4e | %.4e |\n'
                 % (name, h[-1, 0] - h[0, 0], h[-1, 2] / h[0, 2] - 1,
                    h[-1, 6] / h[0, 6] - 1, ke[0], ke[-1], me[0], me[-1]))
    fh.close()

    # ---------------- figures ----------------
    fig, ax = plt.subplots(1, 2, figsize=(11, 4))
    for name, d in C.ARMS1:
        h = C.hst(d)
        ax[0].plot((h[:, 0] - T0) / C.PROT, h[:, 1], label=name)
    ax[0].set_xlabel('rotations since restart (rot 283)')
    ax[0].set_ylabel('dt [s]')
    ax[0].set_title('Comparison 1: dt vs time')
    ax[0].legend(fontsize=8)
    ax[0].grid(alpha=.3)
    for name, d in C.ARMS2:
        h = C.hst(d)
        ax[1].plot(h[:, 0] / C.PROT, h[:, 1], label=name)
    h = C.hst(C.PROD3)
    m = h[:, 0] < 1.1e5
    ax[1].plot(h[m, 0] / C.PROT, h[m, 1], 'k--', lw=1, label='prod3 (nghost=2, plm)')
    ax[1].set_xlabel('rotations from cold start')
    ax[1].set_ylabel('dt [s]')
    ax[1].set_title('Comparison 2: dt vs time (cold start)')
    ax[1].legend(fontsize=8)
    ax[1].grid(alpha=.3)
    fig.tight_layout()
    fig.savefig(C.OUT + 'fig_dt.png', dpi=130)

    fig, ax = plt.subplots(1, 3, figsize=(15, 4))
    for k, key in enumerate(['eos_dfloor', 'eos_efloor', 'eos_tfloor']):
        for name, d in C.ARMS1:
            names, cyc, a = C.evlog(d)
            i = names.index(key)
            n = np.diff(np.concatenate([[cyc[0] - 1], cyc]))
            ax[k].semilogy(cyc, a[:, i] / n, '-', label=name)
        ax[k].set_xlabel('cycle')
        ax[k].set_ylabel(key + ' per cycle')
        ax[k].grid(alpha=.3)
        ax[k].legend(fontsize=7)
    ax[0].set_title('Comparison 1: floor counters per cycle')
    fig.tight_layout()
    fig.savefig(C.OUT + 'fig_floors.png', dpi=130)

    fig, ax = plt.subplots(1, 3, figsize=(15, 4))
    for k, key in enumerate(['eos_dfloor', 'eos_efloor', 'eos_tfloor']):
        for name, d in C.ARMS2:
            names, cyc, a = C.evlog(d)
            i = names.index(key)
            n = np.diff(np.concatenate([[cyc[0] - 1], cyc]))
            ax[k].semilogy(cyc, a[:, i] / n, '-', label=name)
        ax[k].set_xlabel('cycle')
        ax[k].set_ylabel(key + ' per cycle')
        ax[k].grid(alpha=.3)
        ax[k].legend(fontsize=7)
    ax[0].set_title('Comparison 2 (cold start): floor counters per cycle')
    fig.tight_layout()
    fig.savefig(C.OUT + 'fig_floors_recon.png', dpi=130)

    fig, ax = plt.subplots(1, 3, figsize=(15, 4))
    for name, d in C.ARMS1:
        h = C.hst(d)
        x = (h[:, 0] - T0) / C.PROT
        ax[0].plot(x, h[:, 6] / h[0, 6] - 1, label=name)
        ax[1].plot(x, h[:, 7:10].sum(axis=1), label=name)
        ax[2].plot(x, h[:, 10:13].sum(axis=1), label=name)
    for a_, t in zip(ax, ['(E - E0)/E0', 'KE [erg]', 'ME [erg]']):
        a_.set_xlabel('rotations since restart')
        a_.set_ylabel(t)
        a_.grid(alpha=.3)
        a_.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(C.OUT + 'fig_energy.png', dpi=130)
    print('logs.py done')


main()
